### ISSUE TITLE
Me Aparece el siguiente error, como lo soluciono ¿? 

### ISSUE THREAD

**Issue by yaircaballero10** [NewRisus/newrisus_1_1#9]
Fatal error: Uncaught --> Smarty: Unable to load template 'file:modulos/forum/forum..tpl' in 'sections/base_plantilla.tpl' <-- thrown in /home/perudin/public_html/comunidad/lib/smarty/sysplugins/smarty_internal_template.php on line 195

**Comment by joelmiguelvalente** [comment]
Hola, este error corresponde a la versión de **New Risus 2**, lo que debes hacer es ir
views/themes/main/templates/modulos/forum/ y buscar **forum.home.tpl** y renombrarlo por **forum..tpl**
